const data = [{
    "email": "vturfitt0@prnewswire.com",
    "firstName": "Virgilio",
    "lastName": "Turfitt",
    "gender": "Male",
    "experience": 1,
    "personality": "IS"
  }, {
    "email": "thannigane1@com.com",
    "firstName": "Toby",
    "lastName": "Hannigane",
    "gender": "Female",
    "experience": 1,
    "personality": "IN"
  }, {
    "email": "ablasetti2@deliciousdays.com",
    "firstName": "Adham",
    "lastName": "Blasetti",
    "gender": "Male",
    "experience": 0,
    "personality": "EN"
  }, {
    "email": "fphilipot3@shutterfly.com",
    "firstName": "Fair",
    "lastName": "Philipot",
    "gender": "Male",
    "experience": 3,
    "personality": "IN"
  }, {
    "email": "hbalsillie4@theatlantic.com",
    "firstName": "Hymie",
    "lastName": "Balsillie",
    "gender": "Male",
    "experience": 2,
    "personality": "EN"
  }, {
    "email": "jtames5@zimbio.com",
    "firstName": "Junette",
    "lastName": "Tames",
    "gender": "Female",
    "experience": 1,
    "personality": "ES"
  }, {
    "email": "pbacks6@ox.ac.uk",
    "firstName": "Percival",
    "lastName": "Backs",
    "gender": "Male",
    "experience": 1,
    "personality": "ES"
  }, {
    "email": "femblow7@liveinternet.ru",
    "firstName": "Flora",
    "lastName": "Emblow",
    "gender": "Female",
    "experience": 1,
    "personality": "IS"
  }, {
    "email": "phenrot8@php.net",
    "firstName": "Page",
    "lastName": "Henrot",
    "gender": "Male",
    "experience": 1,
    "personality": "IN"
  }, {
    "email": "kpickworth9@booking.com",
    "firstName": "Kimberley",
    "lastName": "Pickworth",
    "gender": "Female",
    "experience": 1,
    "personality": "IN"
  }, {
    "email": "kbriskeya@youtube.com",
    "firstName": "Kath",
    "lastName": "Briskey",
    "gender": "Female",
    "experience": 2,
    "personality": "EN"
  }, {
    "email": "jhoudmontb@economist.com",
    "firstName": "Jacinta",
    "lastName": "Houdmont",
    "gender": "Female",
    "experience": 0,
    "personality": "EN"
  }, {
    "email": "saltoftc@nbcnews.com",
    "firstName": "Sheree",
    "lastName": "Altoft",
    "gender": "Female",
    "experience": 2,
    "personality": "IS"
  }, {
    "email": "sworsallsd@si.edu",
    "firstName": "Susanne",
    "lastName": "Worsalls",
    "gender": "Female",
    "experience": 1,
    "personality": "IS"
  }, {
    "email": "dcrosene@privacy.gov.au",
    "firstName": "Drake",
    "lastName": "Crosen",
    "gender": "Male",
    "experience": 1,
    "personality": "IS"
  }, {
    "email": "jrichardsf@tripod.com",
    "firstName": "Janith",
    "lastName": "Richards",
    "gender": "Female",
    "experience": 3,
    "personality": "IN"
  }, {
    "email": "dduffittg@senate.gov",
    "firstName": "Denni",
    "lastName": "Duffitt",
    "gender": "Female",
    "experience": 0,
    "personality": "IS"
  }, {
    "email": "ugilletth@barnesandnoble.com",
    "firstName": "Uriah",
    "lastName": "Gillett",
    "gender": "Male",
    "experience": 1,
    "personality": "IS"
  }, {
    "email": "krumfordi@wiley.com",
    "firstName": "Karee",
    "lastName": "Rumford",
    "gender": "Female",
    "experience": 1,
    "personality": "IS"
  }, {
    "email": "averickj@slashdot.org",
    "firstName": "Ave",
    "lastName": "Verick",
    "gender": "Male",
    "experience": 1,
    "personality": "IN"
  }]
export default data;